# Generated by Django 6.1 on 2026-09-14 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_experience'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Experience',
        ),
    ]
