# Generated by Django 6.1 on 2026-09-21 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialwork',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
